### ISSUE TITLE
謝謝你完成作業

### ISSUE THREAD

**Issue by azole** [lily516liu/git-workshop-#1]
透過 readme 整理的 markdown 語法，兼顧了練習與筆記，這樣做很棒。

影片心得也整理的很好，在整理筆記時，能多用自己的觀點來紀錄是再好不過的了。透過你的分享，我也覺得學到不少，更開心你在一個氛圍很好的小組裡，我想這些同學們都有機會成為你一生的朋友，在未來職涯上說不定也能互相幫忙，很替你感到開心～

**Comment by lily516liu** [comment]
謝謝老師！
